### ISSUE TITLE
PR Preview is 500 internal server erroring

### ISSUE THREAD

**Issue by mgiuca** [tobie/pr-preview#44] opened 2019-11-04 04:56 UTC
I've seen this on two separate specs today:

- https://github.com/w3c/manifest/pull/768
- https://github.com/WICG/badging/pull/57

> :boom: Error: 500 Internal Server Error :boom:
> PR Preview failed to build. (Last tried on Nov 3, 2019, 4:09 AM UTC).
>
> More
> PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
>
> rotating_light Spec Generator - Spec Generator is the web service used to build specs that rely on ReSpec.
>
> link Related URL
>
> �[33m📡 HTTP Error 520:�[39m > �[36mhttps://rawcdn.githack.com/aarongustafson/manifest/708c3b77cee0b866db234f070db84b04a81e921e/index.html�[39m
> If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please file an issue.

**Comment by tobie** [comment] 2019-11-05 00:10
Yes. I'm noticing this error too. Pinging @neoascetic as this seems to be due to githack returning 520s (I'm getting a lot of those for the past 24 hours, this didn't use to be an issue).

**Comment by marcoscaceres** [comment] 2019-11-05 05:15
Subscribed also... in case it's something being caused by ReSpec.

**Comment by neoascetic** [comment] 2019-11-05 06:44
Hello guys. The issue with githack should be fixed now. Could you please verify?

**Comment by marcoscaceres** [comment] 2019-11-05 06:49
Confirmed it's ok on the badging spec: https://github.com/WICG/badging/pull/62

**Comment by tobie** [comment] 2019-11-05 06:51
Yup. This is working for me too!

Thank you.

Closing now. Feel free to reopen if there are other glitches.

**Closed by tobie** 2019-11-05 06:51 UTC
