### ISSUE TITLE
Support spec per directory

### ISSUE THREAD

**Issue by upsuper** [tobie/pr-preview#19] opened 2018-07-16 04:36 UTC
The spec repo for CSSWG has a large number of specs, mostly one in a directory.

It would probably be helpful if the preview can be configured and generated at a per-directory granularity.

**Comment by tobie** [comment] 2018-08-18 11:41
I'm happy to take a PR or consider contracting options to enable this feature.

**Comment by foolip** [comment] 2019-11-20 10:06
Is this a dupe of https://github.com/tobie/pr-preview/issues/18?

**Comment by tobie** [comment] 2019-11-20 10:58
Pretty much, yes.

**Closed by tobie** 2019-11-20 10:58 UTC
Labels: enhancement
