### ISSUE TITLE
504 error

### ISSUE THREAD

**Issue by eric-schuh** [tobie/pr-preview#125] opened 2022-06-28 19:34 UTC
See w3c-ccg/vc-api-use-cases#13.

![image](https://user-images.githubusercontent.com/22247137/176269837-57d4ab74-9c7c-4479-9f6f-db5daf80558a.png)

**Comment by deniak** [comment] 2022-06-29 03:35
That's indeed a bug with the spec generator caused by an empty `href` in that specification. It should now be [fixed](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c-ccg%2Fvc-api-use-cases%2F97b94bc029fa014240625cf44955c86a06e8d307%2Findex.html%3FisPreview%3Dtrue)

**Comment by tobie** [comment] 2022-06-29 10:25
Thanks. Closing here. Please feel free to repoen if the issue shows up again.

**Closed by tobie** 2022-06-29 10:25 UTC
