### ISSUE TITLE
Error not surfaced properly

### ISSUE THREAD

**Issue by TallTed** [tobie/pr-preview#149] opened 2024-02-02 18:20 UTC
See w3c/vc-data-model#1429.

**Comment by tobie** [comment] 2024-02-03 01:02
Should now be fixed. You'll have to slightly edit the PR's body to kickstart a new build.

**Comment by tobie** [comment] 2024-02-03 09:30
Reopening as the fix I landed doesn't work.

Closing again as a duplicate of #148.

**Closed by tobie** 2024-02-03 09:30 UTC

**Comment by tobie** [comment] 2024-02-05 15:36
Indeed, @TallTed, apologies for the mix-up. What were the odds of two entirely different issues with very similar profiles happening the very same weekend I was at FOSDEM!? Bigger than 0, apparently!
