### ISSUE TITLE
Bikeshed returning HTTP 405 Method Not Allowed

### ISSUE THREAD

**Issue by apasel422** [tobie/pr-preview#148] opened 2024-02-02 13:25 UTC
See WICG/attribution-reporting-api#1154, which has the error output:

```html
<p class='error'>Must use POST to process URL</p>
```

**Comment by tobie** [comment] 2024-02-02 14:18
@plinss any idea what’s going here? This seems to be happening across repositories.

**Comment by plinss** [comment] 2024-02-02 18:17
Yeah, the Bikeshed API service has been getting slammed with bogus requests (1-2 per second) from a bunch of crawlers (several hundred differed IPs all over the world) passing somewhat random URLs to be processed.

I made a few changes:
1. any passed URL must have hosts on an allow list of domains (currently the CSSWG servers, GitHub, and W3C)
2. all requests must be made via POST (as all the crawlers are doing GETs)

All the examples we've ever published using CURL are doing POSTs so this seemed a safe option, but I didn't realize pre-review was doing a GET. Sorry for the bother.

If it's too much bother to change to using a POST I can find some other way of allowing pr-preview.

BTW, it would also be helpful if you could send a distinct UA string.

**Comment by tobie** [comment] 2024-02-03 01:02
Should now be fixed. You'll have to slightly edit the PR's body to kickstart a new build.

**Comment by tobie** [comment] 2024-02-03 09:28
OK, so I don't think that has fixed it.

@plinss: I suspect that you need the query as part of the body of the request and not in the URL. How do you need it formatted?

**Comment by plinss** [comment] 2024-02-03 19:51
Query arguments in the URL are fine (tested and verified), as are form data in the body either urlencoded or multipart (or any combination of query arguments and form data). Are you still seeing a 405 error or something else? Can you point me to logs of the error you're still seeing?

(Also a pr-preview specific UA string would help me find your requests in my logs.)

Note that I don't think #149 is a duplicate of this issue as that seems to be related to [Spec Generator](https://www.w3.org/2015/labs/) and not Bikeshed. It also refers to a 502 error.

**Comment by tobie** [comment] 2024-02-03 19:55
> Note that I don't think https://github.com/tobie/pr-preview/issues/149 is a duplicate of this issue as that seems to be related to [Spec Generator](https://www.w3.org/2015/labs/) and not Bikeshed. It also refers to a 502 error.

Oh!!! Thanks. I had totally missed that. (Currently at FOSDEM where I'm presenting + helping run a workshop, so the timing is less than ideal. :D)

**Comment by plinss** [comment] 2024-02-03 20:04
NP, I also noticed that you may be sending the HTTP method in lower case and I'm doing a case-sensitive test (I'm not sure offhand if your client or my server is normalizing that or not). I made the test for POST be case-insensitive in case that helps.

**Comment by tobie** [comment] 2024-02-03 20:25
@plinss thank you. upper-case the method + added a User-Agent header in https://github.com/tobie/pr-preview/commit/bd4c8a4a7ca4c7e8d5175f2d64a6dad353596ee7. Overall though, you're right and I think the problem is now with Spec Generator. @dontcallmedom / @tidoust, any idea what's up and can you help?

**Comment by dontcallmedom** [comment] 2024-02-05 14:28
paging @deniak on the Spec Generator

**Comment by deniak** [comment] 2024-02-05 15:05
Indeed, there was an issue with spec-generator for document hosted on raw.githubusercontent.com. This is now fixed.

**Closed** 2024-02-05 15:18 UTC
